<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_sender.proto

namespace SenderGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для Sender.SendVoIP
 *
 * Generated from protobuf message <code>senderGrpc.SenderSendVoIPRequestStruct</code>
 */
class SenderSendVoIPRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string push_data = 2;</code>
     */
    protected $push_data = '';
    /**
     * Generated from protobuf field <code>string uuid = 3;</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>int64 time_to_live = 4;</code>
     */
    protected $time_to_live = 0;
    /**
     * Generated from protobuf field <code>string routine_key = 5;</code>
     */
    protected $routine_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type string $push_data
     *     @type string $uuid
     *     @type int|string $time_to_live
     *     @type string $routine_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoSender::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string push_data = 2;</code>
     * @return string
     */
    public function getPushData()
    {
        return $this->push_data;
    }

    /**
     * Generated from protobuf field <code>string push_data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPushData($var)
    {
        GPBUtil::checkString($var, True);
        $this->push_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uuid = 3;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 time_to_live = 4;</code>
     * @return int|string
     */
    public function getTimeToLive()
    {
        return $this->time_to_live;
    }

    /**
     * Generated from protobuf field <code>int64 time_to_live = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeToLive($var)
    {
        GPBUtil::checkInt64($var);
        $this->time_to_live = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string routine_key = 5;</code>
     * @return string
     */
    public function getRoutineKey()
    {
        return $this->routine_key;
    }

    /**
     * Generated from protobuf field <code>string routine_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRoutineKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->routine_key = $var;

        return $this;
    }

}

