<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_sender.proto

namespace SenderGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * формат запроса для Sender.SendTypingEvent
 *
 * Generated from protobuf message <code>senderGrpc.SenderSendTypingEventRequestStruct</code>
 */
class SenderSendTypingEventRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 user_list = 1;</code>
     */
    private $user_list;
    /**
     * Generated from protobuf field <code>string event = 2;</code>
     */
    protected $event = '';
    /**
     * Generated from protobuf field <code>repeated .senderGrpc.EventVersionItem event_version_list = 3;</code>
     */
    private $event_version_list;
    /**
     * Generated from protobuf field <code>string routine_key = 4;</code>
     */
    protected $routine_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $user_list
     *     @type string $event
     *     @type \SenderGrpc\EventVersionItem[]|\Google\Protobuf\Internal\RepeatedField $event_version_list
     *     @type string $routine_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoSender::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 user_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserList()
    {
        return $this->user_list;
    }

    /**
     * Generated from protobuf field <code>repeated int64 user_list = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->user_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event = 2;</code>
     * @return string
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>string event = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .senderGrpc.EventVersionItem event_version_list = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEventVersionList()
    {
        return $this->event_version_list;
    }

    /**
     * Generated from protobuf field <code>repeated .senderGrpc.EventVersionItem event_version_list = 3;</code>
     * @param \SenderGrpc\EventVersionItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEventVersionList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SenderGrpc\EventVersionItem::class);
        $this->event_version_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string routine_key = 4;</code>
     * @return string
     */
    public function getRoutineKey()
    {
        return $this->routine_key;
    }

    /**
     * Generated from protobuf field <code>string routine_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRoutineKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->routine_key = $var;

        return $this;
    }

}

