<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура темплейта
 *
 * Generated from protobuf message <code>authGrpc.ApiKeyTemplateStruct</code>
 */
class ApiKeyTemplateStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 template_id = 1;</code>
     */
    protected $template_id = 0;
    /**
     * Generated from protobuf field <code>int64 order = 2;</code>
     */
    protected $order = 0;
    /**
     * Generated from protobuf field <code>string title = 3;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string uniq_name = 4;</code>
     */
    protected $uniq_name = '';
    /**
     * Generated from protobuf field <code>string description = 5;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>map<string, string> scope_list = 6;</code>
     */
    private $scope_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $template_id
     *     @type int|string $order
     *     @type string $title
     *     @type string $uniq_name
     *     @type string $description
     *     @type array|\Google\Protobuf\Internal\MapField $scope_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 template_id = 1;</code>
     * @return int|string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }

    /**
     * Generated from protobuf field <code>int64 template_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkInt64($var);
        $this->template_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 order = 2;</code>
     * @return int|string
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Generated from protobuf field <code>int64 order = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkInt64($var);
        $this->order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uniq_name = 4;</code>
     * @return string
     */
    public function getUniqName()
    {
        return $this->uniq_name;
    }

    /**
     * Generated from protobuf field <code>string uniq_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqName($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniq_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> scope_list = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getScopeList()
    {
        return $this->scope_list;
    }

    /**
     * Generated from protobuf field <code>map<string, string> scope_list = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setScopeList($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scope_list = $arr;

        return $this;
    }

}

