<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура ответа метода удаления списка апи ключей
 *
 * Generated from protobuf message <code>authGrpc.ApikeyRemoveAllResponseStruct</code>
 */
class ApikeyRemoveAllResponseStruct extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

}

