<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура списка ключей
 *
 * Generated from protobuf message <code>authGrpc.ApiKeyListStruct</code>
 */
class ApiKeyListStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .authGrpc.ApiKeyStruct api_key_list = 1;</code>
     */
    private $api_key_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \AuthGrpc\ApiKeyStruct[]|\Google\Protobuf\Internal\RepeatedField $api_key_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .authGrpc.ApiKeyStruct api_key_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApiKeyList()
    {
        return $this->api_key_list;
    }

    /**
     * Generated from protobuf field <code>repeated .authGrpc.ApiKeyStruct api_key_list = 1;</code>
     * @param \AuthGrpc\ApiKeyStruct[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApiKeyList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AuthGrpc\ApiKeyStruct::class);
        $this->api_key_list = $arr;

        return $this;
    }

}

