<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура списка темплейтов
 *
 * Generated from protobuf message <code>authGrpc.ApiKeyTemplateListStruct</code>
 */
class ApiKeyTemplateListStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .authGrpc.ApiKeyTemplateStruct apikey_template_list = 1;</code>
     */
    private $apikey_template_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \AuthGrpc\ApiKeyTemplateStruct[]|\Google\Protobuf\Internal\RepeatedField $apikey_template_list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .authGrpc.ApiKeyTemplateStruct apikey_template_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApikeyTemplateList()
    {
        return $this->apikey_template_list;
    }

    /**
     * Generated from protobuf field <code>repeated .authGrpc.ApiKeyTemplateStruct apikey_template_list = 1;</code>
     * @param \AuthGrpc\ApiKeyTemplateStruct[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApikeyTemplateList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \AuthGrpc\ApiKeyTemplateStruct::class);
        $this->apikey_template_list = $arr;

        return $this;
    }

}

