<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура запроса метода получения апи ключа
 *
 * Generated from protobuf message <code>authGrpc.ApikeyGetRequestStruct</code>
 */
class ApikeyGetRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string api_key = 1;</code>
     */
    protected $api_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string api_key = 1;</code>
     * @return string
     */
    public function getApiKey()
    {
        return $this->api_key;
    }

    /**
     * Generated from protobuf field <code>string api_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApiKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_key = $var;

        return $this;
    }

}

