<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура запроса метода создания апи ключа
 *
 * Generated from protobuf message <code>authGrpc.ApikeyCreateRequestStruct</code>
 */
class ApikeyCreateRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>int64 expires_at = 2;</code>
     */
    protected $expires_at = 0;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>map<string, string> scope_list = 4;</code>
     */
    private $scope_list;
    /**
     * Generated from protobuf field <code>int64 template_id = 5;</code>
     */
    protected $template_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type int|string $expires_at
     *     @type string $name
     *     @type array|\Google\Protobuf\Internal\MapField $scope_list
     *     @type int|string $template_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expires_at = 2;</code>
     * @return int|string
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Generated from protobuf field <code>int64 expires_at = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->expires_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> scope_list = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getScopeList()
    {
        return $this->scope_list;
    }

    /**
     * Generated from protobuf field <code>map<string, string> scope_list = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setScopeList($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scope_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 template_id = 5;</code>
     * @return int|string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }

    /**
     * Generated from protobuf field <code>int64 template_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkInt64($var);
        $this->template_id = $var;

        return $this;
    }

}

