<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * структура запроса метода авторизации апи ключа
 *
 * Generated from protobuf message <code>authGrpc.ApiTokenAuthenticateRequestStruct</code>
 */
class ApiTokenAuthenticateRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string api_token = 2;</code>
     */
    protected $api_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_id
     *     @type string $api_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string api_token = 2;</code>
     * @return string
     */
    public function getApiToken()
    {
        return $this->api_token;
    }

    /**
     * Generated from protobuf field <code>string api_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setApiToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_token = $var;

        return $this;
    }

}

