<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_auth.proto

namespace AuthGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authGrpc.GetAvailableScopeNamesResponseStruct</code>
 */
class GetAvailableScopeNamesResponseStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<int64, string> scope_names = 5;</code>
     */
    private $scope_names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $scope_names
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoAuth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<int64, string> scope_names = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getScopeNames()
    {
        return $this->scope_names;
    }

    /**
     * Generated from protobuf field <code>map<int64, string> scope_names = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setScopeNames($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT64, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scope_names = $arr;

        return $this;
    }

}

