<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/go_database_controller.proto

namespace DatabaseControllerGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>databaseControllerGrpc.UploadBackupToStorageRequestStruct</code>
 */
class UploadBackupToStorageRequestStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string domino_id = 1;</code>
     */
    protected $domino_id = '';
    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     */
    protected $company_id = 0;
    /**
     * Generated from protobuf field <code>string backup_name = 3;</code>
     */
    protected $backup_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $domino_id
     *     @type int|string $company_id
     *     @type string $backup_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\GoDatabaseController::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string domino_id = 1;</code>
     * @return string
     */
    public function getDominoId()
    {
        return $this->domino_id;
    }

    /**
     * Generated from protobuf field <code>string domino_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDominoId($var)
    {
        GPBUtil::checkString($var, True);
        $this->domino_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     * @return int|string
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Generated from protobuf field <code>int64 company_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompanyId($var)
    {
        GPBUtil::checkInt64($var);
        $this->company_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string backup_name = 3;</code>
     * @return string
     */
    public function getBackupName()
    {
        return $this->backup_name;
    }

    /**
     * Generated from protobuf field <code>string backup_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBackupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->backup_name = $var;

        return $this;
    }

}

